[package]
name = "hydro-iso2d"
version = "0.1.0"
authors = ["Jonathan Zrake <jonathan.zrake@gmail.com>"]
edition = "2018"


[dependencies]
hdf5  = { version = "0.7", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }
